import localFont from "next/font/local"
import "./globals.css"

const pretendard = localFont({
  src: "./fonts/PretendardVariable_1.3.8.woff2",
  display: "swap",
})

const d2Coding = localFont({
  src: [
    { path: "./fonts/D2Coding_1.3.2.ttf", weight: "400" },
    { path: "./fonts/D2CodingBold_1.3.2.ttf", weight: "700" },
  ],
  variable: "--font-d2-coding",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className} ${d2Coding.variable}`}>
        {children}
      </body>
    </html>
  )
}
